# Generated by Django 5.2.5 on 2025-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_auto_20250908_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
