# Generated by Django 5.2.5 on 2025-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_item_availability_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='availability',
        ),
        migrations.AddField(
            model_name='item',
            name='totalQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
