# Generated by Django 5.2.5 on 2025-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_remove_item_availability_item_totalquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='totalQuantity',
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
