# Generated by Django 5.2.4 on 2025-07-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Waiter', 'Waiter'), ('Chef', 'Chef'), ('Manager', 'Manager'), ('Cashier', 'Cashier')], max_length=20)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
