# Generated by Django 5.2.5 on 2025-09-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_table'),
        ('Customer', '0003_auto_20250908_0953'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        # First, delete the old Order model
        migrations.DeleteModel(
            name='Order',
        ),
        # Then create the new Order model with the new structure
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Customer.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Staff.staff')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
