# Generated by Django 5.2.5 on 2025-09-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_alter_customer_phonenumber'),
        ('Order', '0003_auto_20250908_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Customer.customer'),
        ),
    ]
