# Generated by Django 5.2.5 on 2025-09-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
    ]
