# Generated by Django 5.2.5 on 2025-09-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_order_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_',
        ),
    ]
