# Generated by Django 5.2.5 on 2025-09-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_item_availability_item_category'),
        ('Order', '0006_alter_order_table'),
        ('Staff', '0004_remove_staff_mobile_alter_staff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Staff.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='itemID',
            field=models.ForeignKey(db_column='itemID', default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Items.item'),
            preserve_default=False,
        ),
    ]
