# Generated by Django 5.2.5 on 2025-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unitOfMeasure', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reorderLevel', models.PositiveIntegerField(default=0)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'Inventory',
            },
        ),
    ]
