# Generated by Django 5.2.4 on 2025-07-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='orderitem',
        ),
    ]
