# Generated by Django 5.2.5 on 2025-09-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_alter_item_table'),
        ('Order', '0002_alter_order_table'),
        ('OrderItem', '0002_alter_orderitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Order.order'),
            preserve_default=False,
        ),
    ]
